### ISSUE TITLE
UPDATE (or NEW I guess) request to join club

### ISSUE THREAD

**Issue by utlco** [tzipor/1024b-club#3]
Inspired by your site, I created a new home page for myself!
The index.html file is 643 bytes, but it loads a background image that's an svg file of 350 bytes, so altogether 993 bytes. Sometimes GTMetrix includes the size of the headers or something and it adds a few bytes. It links to a local page that is itself 993 bytes, so I'm hoping that is allowed under the 1024b club rules.

```
- Link to GTMetrix results: https://gtmetrix.com/reports/iuyui.com/IXpEZF2i/
- domain: iuyui.com/
- url: https://iuyui.com/
- size: 993 bytes total (index.html 643 bytes, s.svg 350 bytes)
```

**Comment by tzipor** [comment]
According to the GTMetrix results, your total size is 1.2KB due to a 404 error for your favicon adding on 462B. There are ways to get around that, see the source of https://benj.lol for a hint.

**Comment by utlco** [comment]
Hey, thanks! I hadn't checked the waterfall so didn't even notice the favicon 404. Adding <link href=data: rel=icon> solved it (I think). Should be ok now.
A love this idea of super slim websites.
