### ISSUE TITLE
[META] This repo is >3x bigger than website

### ISSUE THREAD

**Issue by Saiv46** [tzipor/1024b-club#9]
Even with compression (7-Zip GUI used)

|Compression | Word size (bit) | Dict size (KB) | Result (B) |
|-------------|-----------------|----------------|------------| 
| None | | | **3111** |
| Deflate | 258 | 32 | 2196 |
| Deflate64 | 257 | 64 | 2196 |
| LZMA | 273 | 64 | 2352 |
| BZip2 | | 100 | 2344 |
| PPMd | 16 | 1000 | **2087** |

**Comment by tzipor** [comment]
The actual website is a single minified HTML file. This can be verified by running a GTMetrix test. This repository includes additional files and the HTML is not minified here so that it is easier for visitors to read.
